In [29]:
%load_ext watermark
%watermark -u -d -v -p numpy,pandas,matplotlib

last updated: 2017-01-17 

CPython 3.5.2
IPython 5.1.0

numpy 1.11.3
pandas 0.19.2
matplotlib 1.5.3


In [2]:
%matplotlib inline

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from pandas import Series, DataFrame
import pandas as pd

# Chapter 5 Getting Started with pandas

## Introduction to pandas Data Structures
### Series

In [3]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [9]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [10]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [11]:
'b' in obj2

True

In [12]:
'e' in obj2

False

* dict から生成

In [14]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [15]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

* 欠損値

In [16]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [18]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

* 名前
    * 列名
    * テーブル名

In [20]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [22]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [25]:
obj.index.name = 'column'
obj.name = 'series'
obj

column
Bob      4
Steve    7
Jeff    -5
Ryan     3
Name: series, dtype: int64

### DataFrame

In [26]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002], 
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [27]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [29]:
frame2 = DataFrame(data, 
                   columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [30]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [31]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [33]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [34]:
frame2['debt']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
Name: debt, dtype: object

In [35]:
frame2['debt'] = 16.5
frame2['debt']

one      16.5
two      16.5
three    16.5
four     16.5
five     16.5
Name: debt, dtype: float64

In [36]:
frame2['debt'] = np.arange(5.)
frame2['debt']

one      0.0
two      1.0
three    2.0
four     3.0
five     4.0
Name: debt, dtype: float64

In [37]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [38]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [39]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [41]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [42]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [43]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [44]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [45]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [46]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [47]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [48]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### Index Objects

In [49]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [50]:
index[1:]

Index(['b', 'c'], dtype='object')

index は変更不可．
これはエラー

In [ ]:
index[1] = 'd'

In [52]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [53]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [55]:
'Ohio' in frame3.columns

True

In [56]:
2003 in frame3.index

False

## Essential Functionality
### Reindexing

In [57]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [58]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [59]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [61]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [62]:
frame = DataFrame(np.arange(9).reshape((3, 3)), 
                  index=['a', 'c', 'd'],
                  columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [63]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [64]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [65]:
frame.reindex(index=['a', 'b', 'c', 'd'], 
              method='ffill', 
              columns=states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [66]:
frame.ix[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping entries from an axis

In [67]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [68]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [69]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [70]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [71]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [72]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [73]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [74]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [75]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Indexing, selection, and filtering

In [76]:
obj = Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [77]:
obj['a']

0.0

In [78]:
obj[0]

0.0

In [79]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [80]:
obj[['b', 'd', 'c']]

b    1.0
d    3.0
c    2.0
dtype: float64

In [81]:
obj[[3, 1]]

d    3.0
b    1.0
dtype: float64

In [82]:
obj[obj < 3]

a    0.0
b    1.0
c    2.0
dtype: float64

In [83]:
obj['a':'c']

a    0.0
b    1.0
c    2.0
dtype: float64

In [84]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [85]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [86]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [88]:
data[['two', 'one']]

two  one
Ohio        1    0
Colorado    5    4
Utah        9    8
New York   13   12

In [89]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [90]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [91]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [92]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
data.ix['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [94]:
data.ix[['Colorado', 'Utah'], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [95]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [96]:
data.ix['Utah']

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [97]:
data.ix[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [98]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### Arithmetic and data alignment

In [99]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [100]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [101]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [102]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                 index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [103]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [104]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

#### Arithmetic methods with fill values

In [105]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [106]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [107]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [108]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [109]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

In [110]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [111]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [112]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [113]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [114]:
series = frame.ix[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [115]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [116]:
series2 = Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int32

In [118]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [119]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [120]:
frame.sub(series3, axis = 0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function application and mapping

In [121]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    1.194253  2.120384  0.366992
Ohio    0.053552  0.665597  1.439469
Texas   0.753622 -2.504979  0.846599
Oregon -0.659705  0.942140  0.120086

In [122]:
frame.abs()

b         d         e
Utah    1.194253  2.120384  0.366992
Ohio    0.053552  0.665597  1.439469
Texas   0.753622  2.504979  0.846599
Oregon  0.659705  0.942140  0.120086

In [123]:
np.abs(frame)

b         d         e
Utah    1.194253  2.120384  0.366992
Ohio    0.053552  0.665597  1.439469
Texas   0.753622  2.504979  0.846599
Oregon  0.659705  0.942140  0.120086

In [126]:
f = lambda x: x.max() - x.min()
f

<function __main__.<lambda>>

In [127]:
frame.apply(f)

b    1.853958
d    4.625363
e    1.319383
dtype: float64

In [128]:
frame.apply(f, axis = 1)

Utah      1.753392
Ohio      1.385918
Texas     3.351578
Oregon    1.601845
dtype: float64

In [129]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])
f

<function __main__.f>

In [130]:
frame.apply(f)

b         d         e
min -0.659705 -2.504979  0.120086
max  1.194253  2.120384  1.439469

In [131]:
frame.apply(f, axis = 1)

min       max
Utah    0.366992  2.120384
Ohio    0.053552  1.439469
Texas  -2.504979  0.846599
Oregon -0.659705  0.942140

In [132]:
format = lambda x: '%.2f' % x
format

<function __main__.<lambda>>

In [133]:
frame.applymap(format)

b      d     e
Utah     1.19   2.12  0.37
Ohio     0.05   0.67  1.44
Texas    0.75  -2.50  0.85
Oregon  -0.66   0.94  0.12

In [134]:
frame['e'].map(format)

Utah      0.37
Ohio      1.44
Texas     0.85
Oregon    0.12
Name: e, dtype: object

### Sorting and ranking

In [135]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [136]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [137]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [139]:
frame.sort_index(ascending=False)

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [142]:
obj = Series([4, 7, -3, 2])
# obj.order() # deprecated
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [143]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [144]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [146]:
# frame.sort_index(by = 'b') # deprecated
frame.sort_values(by = 'b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [147]:
# frame.sort_index(by = 'b') # deprecated
frame.sort_values(by = ['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

* タイは平均

In [148]:
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

* method='first'で先に出てきたものが上

In [149]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [150]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [151]:
frame = DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                   'c': [-2, 5, 8, -2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [152]:
frame.rank(axis = 1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [153]:
frame.rank()

a    b    c
0  1.5  3.0  2.0
1  3.5  4.0  3.0
2  1.5  1.0  4.0
3  3.5  2.0  1.0

### Axis indexes with duplicate values

In [154]:
obj = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [155]:
obj.index.is_unique

False

In [156]:
obj['a']

a    0
a    1
dtype: int32

In [157]:
obj['c']

4

In [158]:
df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -0.752287 -0.591022 -0.247574
a -1.039342 -0.590430  1.678264
b -2.983389 -0.078000 -0.675173
b -0.239130  0.194851 -0.220136

In [160]:
df.ix['a']

0         1         2
a -0.752287 -0.591022 -0.247574
a -1.039342 -0.590430  1.678264

## Summarizing and Computing Descriptive Statistics

In [161]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [162]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [163]:
df.sum(axis = 1)

a    1.40
b    2.60
c     NaN
d   -0.55
dtype: float64

In [164]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [165]:
df.mean(axis=1)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [169]:
df.idxmax()

one    b
two    d
dtype: object

In [170]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [173]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [174]:
obj = Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [175]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

`pandas.io.data` は `pandas-datareader` に分離

```
conda install pandas-datareader
```
`0.2.1` が入る（最新版は`0.3.0`）

---

`dict.iteritems()` は Python3 では削除

* `dict.items` を使う?

```
pydoc -p 1234
```
で `localhost:1234` からドキュメントが見られる

In [11]:
# import pandas.io.data as web
import pandas_datareader.data as web

In [15]:
all_data = {}
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']:
    all_data[ticker] = web.get_data_yahoo(ticker)
price = DataFrame({tic: data['Adj Close'] for tic, data in all_data.items()})
volume = DataFrame({tic: data['Volume'] for tic, data in all_data.items()})

percent change

In [17]:
returns = price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2017-01-09  0.009159  0.000620 -0.011090 -0.003183
2017-01-10  0.001009 -0.002306 -0.012705 -0.000319
2017-01-11  0.005373  0.003877  0.013473  0.009103
2017-01-12 -0.004175 -0.001919  0.001192 -0.009179
2017-01-13 -0.001761  0.001885 -0.003632  0.001437

correlation (Series)

In [18]:
returns.MSFT.corr(returns.IBM)

0.49678673972837339

covariance (Series)

In [19]:
returns.MSFT.cov(returns.IBM)

8.6961239530001922e-05

In [20]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.411552  0.383898  0.393515
GOOG  0.411552  1.000000  0.402753  0.472016
IBM   0.383898  0.402753  1.000000  0.496787
MSFT  0.393515  0.472016  0.496787  1.000000

In [21]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000271  0.000106  0.000076  0.000094
GOOG  0.000106  0.000247  0.000076  0.000108
IBM   0.000076  0.000076  0.000145  0.000087
MSFT  0.000094  0.000108  0.000087  0.000212

In [22]:
returns.corrwith(returns.IBM)

AAPL    0.383898
GOOG    0.402753
IBM     1.000000
MSFT    0.496787
dtype: float64

In [23]:
returns.corrwith(volume)

AAPL   -0.073683
GOOG   -0.008532
IBM    -0.200727
MSFT   -0.091744
dtype: float64

### Unique Values, Value Counts, and Membership