# Chapter 4: NumPy Basics: Arrays and Vectorized Computation

## The NumPy ndarray: A Multidimensional Array Object

In [40]:
%matplotlib inline

In [1]:
import numpy as np

In [4]:
from numpy.random import randn

In [5]:
data = randn(2, 3)
data

array([[ 0.59960559,  0.65209088, -0.00953784],
       [-0.0734103 , -0.10555257, -0.89983851]])

In [6]:
data * 10

array([[ 5.9960559 ,  6.5209088 , -0.0953784 ],
       [-0.73410305, -1.05552567, -8.99838514]])

In [7]:
np.set_printoptions(precision=4, suppress=True)

In [8]:
data

array([[ 0.5996,  0.6521, -0.0095],
       [-0.0734, -0.1056, -0.8998]])

In [9]:
data * 10

array([[ 5.9961,  6.5209, -0.0954],
       [-0.7341, -1.0555, -8.9984]])

In [10]:
data + data

array([[ 1.1992,  1.3042, -0.0191],
       [-0.1468, -0.2111, -1.7997]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

### Creating ndarrays

In [13]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 4)

In [18]:
arr2.dtype

dtype('int32')

In [19]:
arr1.dtype

dtype('float64')

In [20]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [22]:
np.empty((2, 3, 2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [25]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr1

array([ 1.,  2.,  3.])

In [26]:
arr2 = np.array([1, 2, 3], dtype = np.int32)
arr2

array([1, 2, 3])

In [27]:
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [29]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [30]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [31]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [32]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [33]:
numeric_string = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [34]:
numeric_string.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [35]:
int_array = np.arange(10)

In [36]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)

In [37]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [38]:
empty_uint32 = np.empty(8, dtype = 'u4')

In [39]:
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### Operations between Arrays and Scalars

In [42]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [43]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [44]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [45]:
1 / arr 

array([[ 1.    ,  0.5   ,  0.3333],
       [ 0.25  ,  0.2   ,  0.1667]])

In [46]:
arr ** 0.5

array([[ 1.    ,  1.4142,  1.7321],
       [ 2.    ,  2.2361,  2.4495]])

### Basic Indexing and Slicing

In [47]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[5]

5

In [49]:
arr[5:8]

array([5, 6, 7])

In [50]:
arr[5:8] = 12

In [51]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [52]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [53]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [54]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [55]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [56]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr2d[2]

array([7, 8, 9])

In [58]:
arr2d[0][2]

3

In [59]:
arr2d[0, 2]

3

In [61]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
old_values = arr3d[0].copy()

In [64]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[1, 0]

array([7, 8, 9])

#### Indexing with slices

In [67]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [68]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [72]:
arr2d[1, :2]

array([4, 5])

In [73]:
arr2d[2, :1]

array([7])

In [74]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

### Boolean Indexing

In [75]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [76]:
data = randn(7, 4)
data

array([[ 0.4219,  2.8062,  0.7686, -1.3375],
       [ 0.5627, -3.6092, -0.1487,  1.7802],
       [-0.5046, -0.9688, -0.5627,  0.0621],
       [ 0.6783, -0.2458, -0.671 ,  1.4797],
       [ 2.1695, -0.7956,  0.7016, -0.6811],
       [ 0.48  , -0.5065,  0.4467, -1.0823],
       [-0.0904,  0.4452, -0.1575, -1.7845]])

In [77]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [78]:
data[names == 'Bob']

array([[ 0.4219,  2.8062,  0.7686, -1.3375],
       [ 0.6783, -0.2458, -0.671 ,  1.4797]])

In [79]:
data[names == 'Bob', 3]

array([-1.3375,  1.4797])

In [80]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [81]:
data[-(names == 'Bob')]

C:\Users\Wataru\Miniconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  if __name__ == '__main__':


array([[ 0.5627, -3.6092, -0.1487,  1.7802],
       [-0.5046, -0.9688, -0.5627,  0.0621],
       [ 2.1695, -0.7956,  0.7016, -0.6811],
       [ 0.48  , -0.5065,  0.4467, -1.0823],
       [-0.0904,  0.4452, -0.1575, -1.7845]])

In [86]:
data[~(names == 'Bob')]

array([[ 0.5627, -3.6092, -0.1487,  1.7802],
       [-0.5046, -0.9688, -0.5627,  0.0621],
       [ 2.1695, -0.7956,  0.7016, -0.6811],
       [ 0.48  , -0.5065,  0.4467, -1.0823],
       [-0.0904,  0.4452, -0.1575, -1.7845]])

In [87]:
mask = (names == 'Bob') | (names == 'Will')

In [88]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [89]:
data[mask]

array([[ 0.4219,  2.8062,  0.7686, -1.3375],
       [-0.5046, -0.9688, -0.5627,  0.0621],
       [ 0.6783, -0.2458, -0.671 ,  1.4797],
       [ 2.1695, -0.7956,  0.7016, -0.6811]])

In [90]:
data[data < 0] = 0
data

array([[ 0.4219,  2.8062,  0.7686,  0.    ],
       [ 0.5627,  0.    ,  0.    ,  1.7802],
       [ 0.    ,  0.    ,  0.    ,  0.0621],
       [ 0.6783,  0.    ,  0.    ,  1.4797],
       [ 2.1695,  0.    ,  0.7016,  0.    ],
       [ 0.48  ,  0.    ,  0.4467,  0.    ],
       [ 0.    ,  0.4452,  0.    ,  0.    ]])

In [91]:
data[names != 'Joe'] = 7
data

array([[ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.5627,  0.    ,  0.    ,  1.7802],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.48  ,  0.    ,  0.4467,  0.    ],
       [ 0.    ,  0.4452,  0.    ,  0.    ]])

### Fancy indexing

In [92]:
arr = np.empty((8, 4))
arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [95]:
for i in range(8):
    arr[i] = i 
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [96]:
arr[[4, 3, 1, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.],
       [ 6.,  6.,  6.,  6.]])

In [97]:
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [98]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [99]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [100]:
arr[[1,5,7,2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [102]:
arr[np.ix_([1,5,7,2], [0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [103]:
np.ix_([1,5,7,2], [0,3,1,2])

(array([[1],
        [5],
        [7],
        [2]]), array([[0, 3, 1, 2]]))

### Transposing Arrays and Swapping Axes